FROM openjdk:latest
#RUN addgroup -S spring && adduser -S spring -G spring
#USER spring:spring
#ARG JAR_FILE=target/*.jar manual
#ARG JAR_FILE automation
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
COPY src/main/resources/application.properties .
EXPOSE 8080
ENTRYPOINT ["java","-jar","-Djasypt.encryptor.password=mypassword","/app.jar"]